# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

plugins:
    - jekyll-seo-tag
    - jekyll-feed

# Setup
title:            "Frimicc"
tagline:          'Apps & Meanderings'
description:      'Apps & Meanderings'
url:              http://www.frimicc.com
baseurl:          /

author:
  name:           'Michael Friedman'
  url:            https://www.frimicc.com/
  email:          'michael@frimicc.com'
  twitter:        frimicc

paginate:         5

# Custom vars
version:          1.0
github:
  repo:           https://github.com/frimicc/frimicc.github.io
