# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Frimicc"
tagline:          'Apps & Meanderings'
description:      'Apps & Meanderings'
url:              http://www.frimicc.com
baseurl:          /

author:
  name:           'Michael Friedman'
  url:            https://twitter.com/frimicc
  email:          'frimicc@gmail.com'

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/frimicc/frimicc.github.io
